import { useState, useEffect, useCallback } from 'react';
import { io } from 'socket.io-client';

interface ValidationCheck {
  name: string;
  status: 'passed' | 'failed' | 'warning' | 'skipped';
  message: string;
  details?: string[];
}

interface ValidationReport {
  problemId: string;
  status: 'passed' | 'failed' | 'warning';
  duration: number;
  checks: ValidationCheck[];
  benchmarks?: {
    referenceSolution: {
      language: string;
      maxRuntimeMs: number;
      maxMemoryKb: number;
      timeLimitMs: number;
      memoryLimitMb: number;
      withinLimits: boolean;
    };
  };
}

interface ProblemRow {
  id: string;
  title: string;
  difficulty: string;
  readyStatus: 'draft' | 'validating' | 'ready' | 'published';
  hasReferenceSolution: boolean;
  sampleCount: number;
  hiddenCount: number;
  lastValidation: {
    status: 'passed' | 'failed' | 'warning';
    timestamp: string;
  } | null;
}

interface ProblemValidatorProps {
  adminToken: string;
  apiUrl: string;
}

export default function ProblemValidator({ adminToken, apiUrl }: ProblemValidatorProps) {
  const [problems, setProblems] = useState<ProblemRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeReport, setActiveReport] = useState<ValidationReport | null>(null);
  const [validatingId, setValidatingId] = useState<string | null>(null);
  const [batchValidating, setBatchValidating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchProblems = useCallback(async () => {
    try {
      setLoading(true);
      const res = await fetch(`${apiUrl}/admin/problems`, {
        headers: { 'x-admin-token': adminToken },
      });
      if (!res.ok) throw new Error('Failed to load problems');
      const data = await res.json();
      setProblems(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [apiUrl, adminToken]);

  useEffect(() => {
    fetchProblems();
    const socket = io(apiUrl, { transports: ['websocket', 'polling'] });
    socket.on('problems:updated', () => {
      fetchProblems();
    });
    return () => {
      socket.off('problems:updated');
      socket.disconnect();
    };
  }, [fetchProblems, apiUrl]);

  const handleValidate = async (id: string) => {
    setValidatingId(id);
    setActiveReport(null);
    setError(null);
    try {
      const res = await fetch(`${apiUrl}/admin/problems/${id}/validate`, {
        method: 'POST',
        headers: { 'x-admin-token': adminToken },
      });
      if (!res.ok) throw new Error('Validation request failed');
      const report: ValidationReport = await res.json();
      setActiveReport(report);
      fetchProblems();
    } catch (err: any) {
      setError(err.message);
    } finally {
      setValidatingId(null);
    }
  };

  const handleValidateAll = async () => {
    setBatchValidating(true);
    setError(null);
    try {
      const res = await fetch(`${apiUrl}/admin/problems/validate-all`, {
        method: 'POST',
        headers: { 'x-admin-token': adminToken },
      });
      if (!res.ok) throw new Error('Batch validation failed');
      fetchProblems();
    } catch (err: any) {
      setError(err.message);
    } finally {
      setBatchValidating(false);
    }
  };

  const handleUpdateStatus = async (id: string, newStatus: 'draft' | 'ready' | 'published') => {
    setError(null);
    try {
      const res = await fetch(`${apiUrl}/admin/problems/${id}/ready-status`, {
        method: 'PUT',
        headers: {
          'x-admin-token': adminToken,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ status: newStatus }),
      });
      if (!res.ok) {
        const d = await res.json();
        throw new Error(d.error || 'Failed to update problem status');
      }
      fetchProblems();
    } catch (err: any) {
      setError(err.message);
    }
  };

  const handleRegenerateOutputs = async (id: string) => {
    if (!confirm('Warning: This will overwrite expected testcase output (.out) files with outputs generated by the reference solution. Continue?')) return;
    setError(null);
    try {
      const res = await fetch(`${apiUrl}/admin/problems/${id}/regenerate-outputs`, {
        method: 'POST',
        headers: {
          'x-admin-token': adminToken,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ confirm: true }),
      });
      if (!res.ok) {
        const d = await res.json();
        throw new Error(d.error || 'Regeneration failed');
      }
      alert('Outputs successfully generated!');
      fetchProblems();
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Problem Validation</h2>
          <p className="text-sm text-slate-500 mt-1">
            Validate completeness, compile templates, run reference solutions and verify resources before publishing.
          </p>
        </div>
        <button
          onClick={handleValidateAll}
          disabled={batchValidating || loading}
          className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg shadow-sm disabled:opacity-50 transition-colors"
        >
          {batchValidating ? (
            <>
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              Validating All...
            </>
          ) : (
            'Validate All Problems'
          )}
        </button>
      </div>

      {error && (
        <div className="p-4 bg-red-50 border border-red-200 text-red-700 text-sm rounded-lg">
          {error}
        </div>
      )}

      {/* Main panel layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        {/* Problems list */}
        <div className="lg:col-span-2 bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-left text-xs uppercase tracking-wider text-slate-400 font-semibold">
                <th className="py-3 px-4">Problem</th>
                <th className="py-3 px-4">Ready Status</th>
                <th className="py-3 px-4 text-center">Ref Solution</th>
                <th className="py-3 px-4 text-center">Validation Status</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading && problems.length === 0 ? (
                <tr>
                  <td colSpan={5} className="text-center py-8 text-slate-400">Loading...</td>
                </tr>
              ) : (
                problems.map((p) => (
                  <tr key={p.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="py-3.5 px-4">
                      <div className="font-medium text-slate-800">{p.title}</div>
                      <div className="text-xs text-slate-400 font-mono mt-0.5">{p.id}</div>
                    </td>
                    <td className="py-3.5 px-4">
                      <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold uppercase ${
                        p.readyStatus === 'published' ? 'bg-purple-100 text-purple-700' :
                        p.readyStatus === 'ready' ? 'bg-emerald-100 text-emerald-700' :
                        p.readyStatus === 'validating' ? 'bg-blue-100 text-blue-700 animate-pulse' :
                        'bg-slate-100 text-slate-600'
                      }`}>
                        {p.readyStatus}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-center">
                      {p.hasReferenceSolution ? (
                        <span className="text-emerald-600 font-bold">✓ Present</span>
                      ) : (
                        <span className="text-red-500 font-medium">✗ Missing</span>
                      )}
                    </td>
                    <td className="py-3.5 px-4 text-center">
                      {p.lastValidation ? (
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium ${
                          p.lastValidation.status === 'passed' ? 'bg-emerald-50 text-emerald-600 border border-emerald-200' :
                          p.lastValidation.status === 'warning' ? 'bg-amber-50 text-amber-600 border border-amber-200' :
                          'bg-red-50 text-red-600 border border-red-200'
                        }`}>
                          {p.lastValidation.status.toUpperCase()}
                        </span>
                      ) : (
                        <span className="text-slate-400 text-xs">Unvalidated</span>
                      )}
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          onClick={() => handleValidate(p.id)}
                          disabled={validatingId !== null || batchValidating}
                          className="px-3 py-1 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded text-xs font-semibold disabled:opacity-50 transition-colors"
                        >
                          {validatingId === p.id ? 'Running...' : 'Validate'}
                        </button>
                        {p.readyStatus === 'ready' && (
                          <button
                            onClick={() => handleUpdateStatus(p.id, 'published')}
                            className="px-3 py-1 bg-purple-600 hover:bg-purple-700 text-white rounded text-xs font-semibold transition-colors"
                          >
                            Publish
                          </button>
                        )}
                        {p.readyStatus === 'published' && (
                          <button
                            onClick={() => handleUpdateStatus(p.id, 'ready')}
                            className="px-3 py-1 bg-slate-500 hover:bg-slate-600 text-white rounded text-xs font-semibold transition-colors"
                          >
                            Retract
                          </button>
                        )}
                        {p.hasReferenceSolution && (
                          <button
                            onClick={() => handleRegenerateOutputs(p.id)}
                            title="Regenerate expected testcase outputs from reference solution"
                            className="p-1 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded"
                          >
                            ⚙
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Validation report */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 space-y-6">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-100 pb-3">Validation Details</h3>
          {activeReport ? (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <span className="text-xs uppercase text-slate-400 font-bold block">STATUS</span>
                  <span className={`text-xl font-bold ${
                    activeReport.status === 'passed' ? 'text-emerald-600' :
                    activeReport.status === 'warning' ? 'text-amber-500' : 'text-red-500'
                  }`}>
                    {activeReport.status.toUpperCase()}
                  </span>
                </div>
                <div className="text-right">
                  <span className="text-xs uppercase text-slate-400 font-bold block">Duration</span>
                  <span className="text-sm font-semibold text-slate-600">{activeReport.duration}ms</span>
                </div>
              </div>

              {activeReport.benchmarks?.referenceSolution && (
                <div className="bg-slate-50 border border-slate-200 rounded-lg p-3 text-xs space-y-1">
                  <div className="font-semibold text-slate-700">Reference Benchmarks ({activeReport.benchmarks.referenceSolution.language.toUpperCase()}):</div>
                  <div>Max Execution: {activeReport.benchmarks.referenceSolution.maxRuntimeMs}ms (Limit: {activeReport.benchmarks.referenceSolution.timeLimitMs}ms)</div>
                  <div>Max Memory: {Math.round(activeReport.benchmarks.referenceSolution.maxMemoryKb / 1024)}MB (Limit: {activeReport.benchmarks.referenceSolution.memoryLimitMb}MB)</div>
                </div>
              )}

              <div className="space-y-3">
                {activeReport.checks.map((c, i) => (
                  <div key={i} className="border border-slate-100 rounded-lg p-3 space-y-1 text-xs">
                    <div className="flex items-center justify-between font-semibold">
                      <span className="text-slate-800">{c.name}</span>
                      <span className={`${
                        c.status === 'passed' ? 'text-emerald-600' :
                        c.status === 'warning' ? 'text-amber-500' :
                        c.status === 'skipped' ? 'text-slate-400' : 'text-red-500'
                      }`}>
                        {c.status.toUpperCase()}
                      </span>
                    </div>
                    <div className="text-slate-500">{c.message}</div>
                    {c.details && c.details.length > 0 && (
                      <ul className="list-disc pl-4 text-[10px] text-red-600 space-y-0.5 mt-1 bg-red-50/50 p-2 rounded border border-red-100/50">
                        {c.details.map((detail, idx) => (
                          <li key={idx}>{detail}</li>
                        ))}
                      </ul>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="text-center text-slate-400 py-12 text-sm">
              Validate a problem to display its testcase reports, starter template status, and execution timings here.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
