import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from "framer-motion";
import { Trophy, ShieldAlert, X } from "lucide-react";
export default function ComicModal({ isOpen, onClose, status, passedCount, totalCount, runtimeMs, memoryMb, message }) {
    if (!isOpen || status === "IDLE")
        return null;
    const isAccepted = status === "ACCEPTED";
    return (_jsx(AnimatePresence, { children: _jsxs("div", { className: "fixed inset-0 z-50 flex items-center justify-center p-4", children: [_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, onClick: onClose, className: "absolute inset-0 bg-black/75 backdrop-blur-sm cursor-pointer" }), _jsxs(motion.div, { initial: { scale: 0.5, rotate: -15, opacity: 0 }, animate: { scale: 1, rotate: 0, opacity: 1, transition: { type: "spring", stiffness: 120, damping: 10 } }, exit: { scale: 0.5, rotate: 10, opacity: 0 }, className: "relative max-w-lg w-full bg-white border-5 border-black p-6 rounded-2xl shadow-[8px_8px_0_0_rgba(0,0,0,1)] select-none z-10", children: [_jsx("div", { className: "absolute inset-0 opacity-10 rounded-2xl pointer-events-none", style: {
                                backgroundImage: "radial-gradient(circle, #000 2px, transparent 2px)",
                                backgroundSize: "8px 8px"
                            } }), _jsx("button", { onClick: onClose, className: "absolute top-3 right-3 p-1.5 bg-black text-white hover:bg-zinc-800 border-2 border-black rounded-lg transition active:translate-y-0.5 z-20", children: _jsx(X, { className: "w-4 h-4" }) }), isAccepted ? (
                        /* SUCCESS BURST PANEL */
                        _jsxs("div", { className: "text-center relative", children: [_jsxs("div", { className: "relative h-44 flex items-center justify-center mb-3", children: [_jsx("svg", { className: "absolute w-64 h-64 text-yellow-300 drop-shadow-[4px_4px_0_rgba(0,0,0,1)]", viewBox: "0 0 100 100", children: _jsx("polygon", { points: "50,0 60,35 95,20 70,50 100,70 65,70 75,100 50,80 25,100 35,70 0,70 30,50 5,20 40,35", fill: "currentColor", stroke: "#000", strokeWidth: "2" }) }), _jsxs(motion.div, { initial: { scale: 0.2 }, animate: { scale: [1, 1.2, 1], rotate: [-5, 5, -3] }, transition: { duration: 0.5, repeat: Infinity, repeatType: "reverse" }, className: "relative flex flex-col items-center justify-center z-10", children: [_jsx("span", { className: "font-comic text-7xl uppercase italic tracking-wider text-red-600 stroke-black drop-shadow-[3px_3px_0_rgba(0,0,0,1)] comic-title", children: "POW!" }), _jsx("span", { className: "font-comic text-4xl uppercase tracking-widest text-green-700 stroke-white drop-shadow-[2px_2px_0_rgba(0,0,0,1)] bg-yellow-100 border-3 border-black py-1 px-4 rounded transform rotate-3 -mt-1 flex items-center gap-1.5 shadow-[2px_2px_0_rgba(0,0,0,1)] comic-title", children: "MISSION COMPLETE \u2713" })] })] }), _jsxs("div", { className: "bg-yellow-100 border-3 border-black rounded-xl p-3.5 shadow-[3px_3px_0_0_rgba(0,0,0,1)] transform -rotate-1 relative z-10 mb-4", children: [_jsxs("h4", { className: "font-sans font-black text-sm uppercase text-black mb-1.5 flex items-center justify-center gap-2", children: [_jsx(Trophy, { className: "w-5 h-5 text-yellow-500 animate-bounce" }), "Dimension Connected!"] }), _jsxs("div", { className: "font-mono text-xs text-zinc-900 space-y-1", children: [_jsxs("div", { className: "font-extrabold text-green-700", children: ["\u2713 ", passedCount, "/", totalCount, " Test Cases Passed"] }), _jsxs("div", { className: "text-zinc-600 font-semibold", children: ["Runtime: ", _jsxs("span", { className: "text-black font-black", children: [runtimeMs, "ms"] })] }), _jsxs("div", { className: "text-zinc-600 font-semibold", children: ["Memory: ", _jsxs("span", { className: "text-black font-black", children: [memoryMb, "MB"] })] })] })] }), _jsx("p", { className: "font-mono text-xs text-zinc-700 font-bold mb-2 text-center", children: "\uD83D\uDD78\uFE0F Thwip! Miles' neural networks have synchronized with the Multiverse anchors!" })] })) : (
                        /* CRASH / FAIL BURST PANEL */
                        _jsxs("div", { className: "text-center relative", children: [_jsxs("div", { className: "relative h-44 flex items-center justify-center mb-3", children: [_jsx("svg", { className: "absolute w-64 h-64 text-zinc-800 drop-shadow-[4px_4px_0_rgba(0,0,0,1)]", viewBox: "0 0 100 100", children: _jsx("polygon", { points: "50,0 58,30 90,15 68,48 98,68 62,68 70,98 50,78 30,98 38,68 2,68 32,48 10,15 42,30", fill: "currentColor", stroke: "#000", strokeWidth: "2.5" }) }), _jsxs(motion.div, { initial: { scale: 0.2 }, animate: { scale: [1, 1.15, 1], rotate: [3, -3, 3] }, transition: { duration: 0.5, repeat: Infinity, repeatType: "reverse" }, className: "relative flex flex-col items-center justify-center z-10", children: [_jsx("span", { className: "font-comic text-7xl uppercase italic tracking-wider text-yellow-300 stroke-black drop-shadow-[3px_3px_0_rgba(0,0,0,1)] comic-title", children: "CRASH!" }), _jsx("span", { className: "font-comic text-3xl uppercase tracking-widest text-red-500 stroke-white drop-shadow-[2px_2px_0_rgba(0,0,0,1)] bg-zinc-900 border-3 border-black py-1 px-4 rounded transform -rotate-2 -mt-1 flex items-center gap-1.5 shadow-[2px_2px_0_rgba(0,0,0,1)] comic-title", children: "FAILED \u2717" })] })] }), _jsxs("div", { className: "bg-red-50 border-3 border-black rounded-xl p-3.5 shadow-[3px_3px_0_0_rgba(0,0,0,1)] transform rotate-1 relative z-10 mb-4 text-left", children: [_jsxs("h4", { className: "font-sans font-black text-sm uppercase text-red-600 mb-1.5 flex items-center gap-2", children: [_jsx(ShieldAlert, { className: "w-5 h-5 text-red-600 animate-bounce" }), "Dimension Anomaly Detected"] }), _jsxs("div", { className: "font-mono text-xs text-zinc-800 space-y-1", children: [_jsxs("div", { className: "font-extrabold text-red-600", children: ["\u2717 Only ", passedCount, "/", totalCount, " Cases Validated"] }), message && (_jsx("div", { className: "bg-white border border-red-300 p-2 rounded text-[10px] text-red-800 whitespace-pre-wrap leading-tight mt-2 max-h-20 overflow-y-auto", children: message }))] })] }), _jsx("p", { className: "font-mono text-xs text-zinc-700 font-bold mb-2 text-center", children: "\u26A1 Use your Spider-Sense or refill Web-Fluid to debug the synchronization anomaly!" })] })), _jsx("div", { className: "flex gap-2.5 justify-center relative z-10 mt-4", children: _jsx("button", { onClick: onClose, className: "bg-zinc-950 text-white hover:bg-zinc-800 font-sans font-black tracking-wide text-xs uppercase border-3 border-black rounded-lg py-2 px-5 shadow-[3px_3px_0_0_rgba(0,0,0,1)] active:translate-y-0.5 active:shadow-none transition cursor-pointer", children: "Back to Terminal" }) })] })] }) }));
}
//# sourceMappingURL=ComicModal.js.map