import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { ShieldAlert, Send, X } from 'lucide-react';
export default function SuitTechModal({ isOpen, onClose, onConfirm, isPending = false, currentProblemTitle = 'Current Mission' }) {
    if (!isOpen)
        return null;
    return (_jsx(AnimatePresence, { children: _jsxs("div", { className: "fixed inset-0 z-50 flex items-center justify-center p-4", children: [_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, onClick: onClose, className: "absolute inset-0 bg-black/70 backdrop-blur-[6px] cursor-pointer" }), _jsxs(motion.div, { initial: { scale: 0.9, opacity: 0, y: 10 }, animate: { scale: 1, opacity: 1, y: 0 }, exit: { scale: 0.9, opacity: 0, y: 10 }, className: "relative w-full max-w-lg bg-[#0d1117] border-3 border-sky-500 p-6 shadow-[6px_6px_0_#0284c7] z-10 font-sans text-white select-none", children: [_jsx("button", { onClick: onClose, className: "absolute top-4 right-4 text-slate-400 hover:text-white", children: _jsx(X, { className: "w-5 h-5" }) }), _jsxs("div", { className: "flex items-center gap-3 border-b border-sky-500/30 pb-3 mb-4", children: [_jsx("div", { className: "w-10 h-10 bg-sky-600/20 border-2 border-sky-400 flex items-center justify-center text-sky-400", children: _jsx(ShieldAlert, { className: "w-6 h-6 animate-pulse" }) }), _jsxs("div", { children: [_jsx("h2", { className: "font-display font-black text-lg uppercase tracking-wider text-sky-400", children: "SUIT TECH \u2022 SPIDER-COMMS" }), _jsx("p", { className: "font-mono text-xs text-slate-400", children: "Tactical Assistance Relay" })] })] }), _jsxs("div", { className: "space-y-3 font-mono text-xs mb-6", children: [_jsxs("div", { className: "bg-sky-950/40 border border-sky-500/40 p-3 rounded text-slate-200", children: [_jsx("span", { className: "text-sky-300 font-bold uppercase", children: "TARGET MISSION: " }), _jsx("span", { className: "font-extrabold text-white", children: currentProblemTitle })] }), _jsx("p", { className: "text-slate-300 leading-relaxed", children: "Request direct tactical guidance from the Spider-Vision Command Center for this mission." }), _jsxs("div", { className: "bg-yellow-950/30 border border-yellow-500/40 p-2.5 text-yellow-300 text-[11px]", children: ["\u26A0\uFE0F ", _jsx("span", { className: "font-bold", children: "Notice:" }), " Only 1 pending assistance request is permitted at a time. Charges are deducted immediately upon dispatch."] }), isPending && (_jsx("div", { className: "bg-amber-900/60 border border-amber-500 text-amber-200 p-2.5 text-center font-bold animate-pulse", children: "\u23F3 A request is currently pending response from HQ." }))] }), _jsxs("div", { className: "flex justify-end gap-3 font-mono text-xs font-bold uppercase", children: [_jsx("button", { onClick: onClose, className: "px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-600 shadow-[2px_2px_0_#000]", children: "Cancel" }), _jsxs("button", { disabled: isPending, onClick: () => {
                                        onConfirm();
                                        onClose();
                                    }, className: `px-5 py-2 flex items-center gap-2 border-2 border-black shadow-[3px_3px_0_#000] ${isPending
                                        ? 'bg-slate-700 text-slate-400 cursor-not-allowed'
                                        : 'bg-sky-500 hover:bg-sky-400 text-black font-extrabold active:translate-y-0.5 active:shadow-none cursor-pointer'}`, children: [_jsx(Send, { className: "w-4 h-4" }), isPending ? 'Request Pending' : 'Request Assistance'] })] })] })] }) }));
}
//# sourceMappingURL=SuitTechModal.js.map